/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import com.indvd00m.ascii.render.Render;
import com.indvd00m.ascii.render.api.ICanvas;
import com.indvd00m.ascii.render.api.IContextBuilder;
import com.indvd00m.ascii.render.api.IRender;
import com.indvd00m.ascii.render.elements.PseudoText;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType0Font;

import java.io.File;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        IRender render = new Render();
		IContextBuilder builder = render.newBuilder();
		builder.width(120).height(10);
		builder.element(new PseudoText("Pascal DevOps W4"));
		ICanvas canvas = render.render(builder.build());
		String s = canvas.getText();
		System.out.println(s);

        try {
            // Create a new document
            PDDocument document = new PDDocument();
            PDPage page = new PDPage();
            document.addPage(page);

            // Load the TTF font from a file
            File fontFile = new File("/Users/pascalaigner/myCloud/01 Studium/ZHAW/Master Wirtschaftsinformatik/2. Semester/DevOps/Woche 4/AlphacodePharaohRegular-JRdOB.ttf");
            PDType0Font font = PDType0Font.load(document, fontFile);

            // Create a content stream to write text to the page
            PDPageContentStream contentStream = new PDPageContentStream(document, page);
            contentStream.beginText();
            contentStream.setFont(font, 50);
            contentStream.newLineAtOffset(100, 700);
            contentStream.showText("Hello, World!");
            contentStream.endText();
            contentStream.close();

            // Save the document to the desired path
            String outputPath = "/Users/pascalaigner/myCloud/01 Studium/ZHAW/Master Wirtschaftsinformatik/2. Semester/DevOps/Woche 4/HelloWorld.pdf";
            document.save(outputPath);
            document.close();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
}
